---
# File: tasks/Debian.yml - Debian tasks for ansible-couchbase-server

## Couchbase Server Enterprise Edition

- name: Download package locally
  become: no
  connection: local
  get_url: "url={{ couchbase_server_debian_ee_url }} dest={{ role_path }}/files/{{ couchbase_server_debian_ee_package }} sha256sum={{ couchbase_server_debian_ee_sha256 }} timeout=240"
  run_once: true
  when: couchbase_server_edition == "enterprise" and couchbase_server_local_package != true
  tags: installation

- name: Copy package
  copy: "src={{ couchbase_server_debian_ee_package }} dest=/tmp/{{ couchbase_server_debian_ee_package }}"
  when: couchbase_server_edition == "enterprise" and couchbase_server_local_package != true
  tags: installation

- name: Install package
  become: yes
  become_user: root
  apt: "deb=/tmp/{{ couchbase_server_debian_ee_package }} state=present"
  when: couchbase_server_edition == "enterprise"
  tags: installation

- name: Package file cleanup
  become: yes
  become_user: root
  file: "dest=/tmp/{{ couchbase_server_debian_ee_package }} state=absent"
  when: couchbase_server_edition == "enterprise"
  tags: installation

## Couchbase Server Community Edition

- name: Download package locally
  become: no
  connection: local
  get_url: "url={{ couchbase_server_debian_ce_url }} dest={{ role_path }}/files/{{ couchbase_server_debian_ce_package }} sha256sum={{ couchbase_server_debian_ce_sha256 }} timeout=240"
  run_once: true
  when: couchbase_server_edition == "community" and couchbase_server_local_package != true
  tags: installation

- name: Copy package
  copy: "src={{ couchbase_server_debian_ce_package }} dest=/tmp/{{ couchbase_server_debian_ce_package }}"
  when: couchbase_server_edition == "community" and couchbase_server_local_package != true
  tags: installation

- name: Install package
  become: yes
  become_user: root
  apt: "deb=/tmp/{{ couchbase_server_debian_ce_package }} state=present"
  when: couchbase_server_edition == "community"
  tags: installation

- name: Package file cleanup
  become: yes
  become_user: root
  file: "dest=/tmp/{{ couchbase_server_debian_ce_package }} state=absent"
  when: couchbase_server_edition == "community"
  tags: installation

# Firewall (optional)
- name: Firewall limitations
  include: Debian_firewall.yml
  when: couchbase_server_firewall == True
